config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
<<<<<<< HEAD
  root 'welcome#index'

	resources :users do
	    collection do
	        get :profile
	    end
	end

=======
  root 'products#index'

  resources :products, only:[ :index, :show] do
		member do
			post :add_to_cart
		end
	end

	resource :carts
	resources :orders

	namespace :admin do
		root 'orders#index'
		resources :products
		resources :orders
	end
>>>>>>> book

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
<<<<<<< HEAD
=======

	has_many :cart_items, dependent: :destroy
	has_many :products, through: :cart_items

	def add_cart_item(product)
    existing_item = self.cart_items.find_by( product_id: product )
    if existing_item
      existing_item.quantity += 1
      existing_item.save!
    else
      cart_item = cart_items.build( :product_id => product.id, :quantity => 1  )
      cart_item.save!
    end
    self.cart_items
  end

  def total
    cart_items.map{ |x| x.subtotal }.sum
  end

  def total_quantity
    cart_items.map{ |x| x.quantity }.sum
  end

  def find_item_by(product)
    self.cart_items.where(product_id: product).first
  end


>>>>>>> book
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :cart
  belongs_to :product

  def subtotal
    self.quantity * self.product.price
  end

end

app/models/order.rb
class Order < ApplicationRecord

validates_presence_of :name, :email, :address, :phone, :payment_method

  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  enum payment_method: [ :credit, :atm]
  enum order_status: [ :new_order, :shipped, :cancelled]
  enum payment_status: [ :atm_pending, :atm_paid, :credit_pending, :credit_paid]

  def add_order_items(cart)
    cart.cart_items.each do |item|
      self.order_items.build( product_id: item.product.id,
                              quantity: item.quantity,
                              price: item.product.price )
    end
  end

  def init_status
    if self.payment_method == "atm"
      self.payment_status = "atm_pending"
    else
      self.payment_status = "credit_pending"
    end
  end
	
end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

end

app/models/product.rb
class Product < ApplicationRecord
<<<<<<< HEAD
=======

  validates_presence_of :name, :price, :in_stock_qty

  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items

  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

>>>>>>> book
end

app/models/profile.rb
class Profile < ApplicationRecord

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :orders

  def admin?
  	self.role == "admin"
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update]

  def index
    @orders = Order.all
  end

  def update
    @order.update(order_params)
    redirect_to admin_orders_path, notice: 'Date update.'
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:name, :email, :phone, :address, :amount, :payment_method, :payment_status, :order_status)
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_user!  # 這個是 devise 提供的方法，先檢查必須登入
  before_action :authenticate_admin # 再檢查是否有權限
  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path, notice: 'product was successfully created'
    else
      render new_admin_product_path
    end
  end

  def update
    if @product.update(product_params)
      redirect_to admin_products_path, notice: 'update successfully'
    else
      render action: :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, alert: 'product deleted.'
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, 
                                      :price, 
                                      :image_url, 
                                      :description, 
                                      :in_stock_qty)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

<<<<<<< HEAD
  # before :find_cart

  def find_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
        @cart = Cart.create
        session[:cart_id] = @cart.id
    end
  end
end
=======
  # 注意這裡的位置是 Application Controller，由於 Cookie - Session 和瀏覽器有關，我們必須將這個方法放在 controller 裡（而非移到 model）
  # 另外，在 View 裡呼叫 Controller 方法時，必須使用 helper_method

  helper_method :current_cart

  protected

  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end

  def current_cart
    @cart || set_cart # 如果 @cart 存在就回傳 @cart，否則呼叫 set_cart 方法
  end

  def set_cart
    # 根據 session 來搜尋特定 Cart
    if session[:cart_id]
      @cart = Cart.find_by(id: session[:cart_id])
    end

    @cart ||= Cart.create
    # 若 session[:cart_id] 存在，此時 @cart 會回傳 True；然而，若 session[:cart_id] 不存在，此時 @cart = nil，那麼就執行 Cart.create 並寫入 @cart
    # 注意我們不使用 if..else.. 因為我們希望無論遇到任何情況，只要 @cart = nil，在這裡我們都能獲取一個 @cart

    session[:cart_id] = @cart.id
    @cart
  end

end
>>>>>>> book

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # before_action :authenticate_user!
  # Visitor 在這裡第一次登入，成為 Customer

  def new
    @order = current_user.orders.build(email: current_user.email)
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = current_user.orders.build(order_params)
    @order.add_order_items(current_cart)
    @order.amount = current_cart.total
    @order.init_status

    if @order.save
      current_cart.destroy
      redirect_to order_path(@order), notice: '已結帳！'
      UserMailer.notify_order_create(@order).deliver_now!
    else
      render :new
    end
  end

  protected

  def order_params
    params.require(:order).permit(:name, :email, :phone, :address, :payment_method)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
<<<<<<< HEAD
end
=======

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.add_cart_item(@product)
    @item = current_cart.find_item_by(@product)

    redirect_to root_path
    # respond_to do |format|
    #   format.js
    # end
  end

end
>>>>>>> book

app/controllers/users_controller.rb
class UsersController < ApplicationController

	

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	#<%= @orders.errors.full_messages %>
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/orders/edit.html.erb
<h1>Admin: Edit Order</h1>

<%= render partial: "shared/order_list", locals: { order: @order} %>

<hr>

<%= form_for [:admin, @order] do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :payment_method %>
    <%= f.collection_select :payment_method, Order.payment_methods, :first, :first  %>
  </div>
  <div>
    <%= f.label :payment_status %>
    <%= f.collection_select :payment_status, Order.payment_statuses, :first, :first  %>
  </div>
  <div>
    <%= f.label :order_status %>
    <%= f.collection_select :order_status, Order.order_statuses, :first, :first  %>
  </div>

  <%= f.submit %>
<% end %>

app/views/admin/orders/index.html.erb
<h1>Admin: Order Index</h1>
<table>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>email</th>
    <th>phone</th>
    <th>address</th>
    <th>訂單金額</th>
    <th>付款方式</th>
    <th>訂單狀態</th>
    <th>金流狀態</th>
    <th></th>
    <th></th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.name %></td>
      <td><%= order.email %></td>
      <td><%= order.phone %></td>
      <td><%= order.address %></td>
      <td><%= order.amount %></td>
      <td><%= order.payment_method %></td>
      <td><%= order.order_status %></td>
      <td><%= order.payment_status %></td>
      <td><%= link_to 'show', admin_order_path(order)%></td>
      <td><%= link_to 'edit', edit_admin_order_path(order) %></td>
    </tr>
  <% end %>
</table>

app/views/admin/orders/show.html.erb
<%= render partial: "shared/order_list", locals: { order: @order} %>

app/views/admin/products/edit.html.erb
<%= render partial: "shared/product", locals: { product: @product} %>

app/views/admin/products/index.html.erb
<h1>Admin: <%= controller_name %>#<%= action_name %></h1>

<%= link_to 'Add new product', new_admin_product_path %>

<%= paginate @products %>
<table>
  <tr>
    <th>商品名稱</th>
    <th>圖示</th>
    <th>單價</th>
    <th>庫存量</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= image_tag(product.image_url, width: 30 ) %></td>
      <td>$<%= product.price %></td>
      <td><%= product.in_stock_qty %></td>
      <td><%= link_to 'show', product_path(product) %></td>
      <td><%= link_to 'edit', edit_admin_product_path(product.id) %></td>
      <td><%= link_to 'delete', admin_product_path(product.id), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<%= render partial: "shared/product", locals: { product: @product} %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">  Copyright ©2017 AC camp
    <br>Design by
    <a href="#"> Paul & Ray</a>
  </p>

</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">Shopping</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to("Sign_in","#") %>

        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcExerciseShoppingCart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <div class="container">
      <% if current_user %>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to('註冊', new_registration_path(:user)) %>
        <%= link_to('登入', new_session_path(:user)) %>
      <% end %>
    </div>
    <div class="container">
      <%= render "common/navbar" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/orders/new.html.erb
<%= form_for @order do |f| %>

  <% if @order.errors.any? %>
    <% @order.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :payment_method %>
    <%= f.collection_select :payment_method, Order.payment_methods, :first, :first  %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/orders/show.html.erb
<%= render partial: "shared/order_list", locals: { order: @order} %>

app/views/products/index.html.erb
<<<<<<< HEAD
<%= link_to product_path(product) do %>
    <%= image_tag(product.image_url) %>
    <%= product.name %>
    <%= product.price %>
<% end %>
=======
<h1>公仔達人</h1>

<section id="my-cart">
  <strong>你目前選購了 <span id="cart-total-qty"><%= current_cart.total_quantity %></span> 件商品，預計消費 <span id="cart-total"><%= current_cart.total %></span> 元
  </strong>
  <table>
    <tr>
      <th>商品</th>
      <th>單價</th>
      <th>數量</th>
      <th>小計</th>
    </tr>
    <% current_cart.cart_items.each do |item| %>
      <%= render partial: 'shared/item', locals: { item: item }%>
    <% end %>
  </table>
  <%= link_to '我要結帳！', new_order_path %>
</section>


<div class="container">	
	<div class="row">
		<% @products.each do |product| %>
			<div class="col-xs-6 col-md-3">
				<P><%= image_tag(product.file_location, :width => 50) %></P>
				<p><%= link_to product.name, product_path(product) %></p>
				<p>$<%= product.price %>
						<%= link_to '+', add_to_cart_product_path(product), :method => :post, :remote => true %></p>
			</div>
		<% end %>
	</div>
</div>

>>>>>>> book

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<%= image_tag(@product.image_url, :width => 200) %>
<p class = "description">
  <%= @product.description %>
</p>
price: $<%= @product.price %><br>
stock: <%= @product.in_stock_qty %>

<p><%= link_to 'back to index', root_path %></p>

app/views/shared/_item.html.erb
<tr>
  <td><%= item.product.name %></td>
  <td><%= item.product.price %></td>
  <td class="cart-<%= item.product.id %>-qty"><%= item.quantity %></td>
  <td class="cart-<%= item.product.id %>-subtotal"><%= item.subtotal %></td>
</tr>

app/views/shared/_order_list.html.erb
<h1>Order #<%= @order.id %></h1>

訂單時間：<%= @order.created_at.strftime('%Y-%m-%d %H:%M')%><br>
收件人：<%= @order.name %><br>
信箱：<%= @order.email %><br>
電話：<%= @order.phone %><br>
地址：<%= @order.address %><br>

<br>
<table>
  <tr>
    <th>訂購商品</th>
    <th>數量</th>
    <th>單價</th>
    <th>小計</th>
  </tr>
  <% @order.order_items.each do |item| %>
    <tr>
      <td><%= item.product.name %></td>
      <td><%= item.quantity %></td>
      <td><%= item.price %></td>
      <td><%= item.quantity * item.price %></td>
    </tr>
  <% end %>
</table>
<br>
<strong>總計: $ <%= @order.amount %></strong>

app/views/shared/_product.html.erb
<h1>Admin: <%= controller_name %>#<%= action_name %></h1>

<%= form_for [:admin, product] do |f| %>
  <%= product.errors.full_messages.to_sentence if product.errors.any? %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <br>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :in_stock_qty %>
  <%= f.number_field :in_stock_qty %>
  <br>
  <%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<h1>  Hello word~~~</h1>
<%= link_to("test", "#", class:"btn btn-primary") %>